baseURL = "https://benpm.github.io/"
languageCode = "en-us"
title = "benpm.github.io"
theme = "hugo-theme-codex"

googleAnalytics = "G-PPST2B8G8Z"

[params]
    twitter = "https://twitter.com/_bpmw"
    github = "https://github.com/benpm"
    youtube = "https://www.youtube.com/c/BenjaminMastripolito"
    soundcloud = "https://soundcloud.com/trope"
    itchio = "https://ben-m.itch.io/"
    ko-fi = "https://ko-fi.com/benpm"
    iconTitles = ["youtube", "soundcloud", "itchio", "ko-fi"]
    dateFormat = "Jan 2006"

[markup]
    [markup.highlight]
        style = "manni"

[markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
    weight = 1
    identifier = ""
    name = "Splash!"
    title = "Splash!"
    url = "/"

[[menu.main]]
    weight = 20
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog"

[[menu.main]]
    weight = 15
    identifier = "professional"
    name = "Professional"
    title = "Professional"
    url = "/professional"

[[menu.main]]
    weight = 17
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects"

[[menu.main]]
    weight = 40
    identifier = "music"
    name = "Music"
    title = "Music"
    url = "/music"

[[menu.main]]
    weight = 50
    identifier = "cv"
    name = "Résumé [pdf]"
    title = "Résumé [pdf]"
    url = "https://github.com/benpm/cv/raw/master/benpm_cv.pdf"